-- ============================================================
-- and° Academy - データベーススキーマ
-- Supabase の SQL Editor に貼り付けて実行する
-- ============================================================

-- 組織（法人アカウント）
create table if not exists organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  access_enabled boolean not null default false,
  created_at timestamptz not null default now()
);

-- プロフィール（auth.users を拡張。ロールと所属組織を持つ）
create table if not exists profiles (
  id uuid primary key references auth.users on delete cascade,
  org_id uuid references organizations on delete set null,
  email text,
  full_name text,
  role text not null default 'member' check (role in ('admin', 'manager', 'member')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- 講座
create table if not exists courses (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  thumbnail_url text,
  audience text not null default 'employee' check (audience in ('executive', 'employee')),
  sort_order int not null default 0,
  published boolean not null default false,
  created_at timestamptz not null default now()
);

-- レッスン（講座内の動画。video_url はプロバイダ非依存）
create table if not exists lessons (
  id uuid primary key default gen_random_uuid(),
  course_id uuid not null references courses on delete cascade,
  title text not null,
  description text,
  video_url text,
  duration_seconds int,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

-- 視聴進捗（ユーザー × レッスン）
create table if not exists lesson_progress (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users on delete cascade,
  lesson_id uuid not null references lessons on delete cascade,
  completed boolean not null default false,
  completed_at timestamptz,
  last_position_seconds int not null default 0,
  updated_at timestamptz not null default now(),
  unique (user_id, lesson_id)
);

-- 許可リスト（招待制。ここに登録されたメールだけがログイン/登録できる）
create table if not exists allowed_emails (
  email text primary key,
  role text not null default 'member' check (role in ('admin', 'manager', 'member')),
  org_id uuid references organizations on delete set null,
  active boolean not null default true,
  invited_by uuid references auth.users on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_lessons_course on lessons (course_id);
create index if not exists idx_progress_user on lesson_progress (user_id);
create index if not exists idx_profiles_org on profiles (org_id);
create unique index if not exists allowed_emails_lower_email_key
  on allowed_emails (lower(email));

-- メンバーごとの講座締切
create table if not exists course_deadlines (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references organizations on delete cascade,
  user_id uuid not null references profiles on delete cascade,
  course_id uuid not null references courses on delete cascade,
  due_date date not null,
  created_by uuid references auth.users on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, course_id)
);

create index if not exists idx_course_deadlines_org on course_deadlines (org_id);
create index if not exists idx_course_deadlines_user
  on course_deadlines (user_id);

-- 組織ごとの受講可能講座
create table if not exists organization_courses (
  org_id uuid not null references organizations on delete cascade,
  course_id uuid not null references courses on delete cascade,
  assigned_by uuid references auth.users on delete set null,
  created_at timestamptz not null default now(),
  primary key (org_id, course_id)
);

create index if not exists idx_organization_courses_course
  on organization_courses (course_id);

-- 管理操作の監査ログ
create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  org_id uuid references organizations on delete set null,
  actor_id uuid references auth.users on delete set null,
  action text not null,
  target_type text not null,
  target_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_logs_org_created
  on audit_logs (org_id, created_at desc);

-- ============================================================
-- 新規ユーザー登録時に profiles を自動作成
-- ============================================================
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  a public.allowed_emails%rowtype;
begin
  -- 許可リストにないメールは登録を拒否（auth.users への挿入ごとロールバック）
  select * into a from public.allowed_emails
  where lower(email) = lower(new.email);

  if not found or not a.active then
    raise exception 'not_allowed: % は招待されていません', new.email;
  end if;

  -- role / org は許可リストから付与（本人は変更できない）
  insert into public.profiles (id, email, full_name, role, org_id, active)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data ->> 'full_name',
    a.role,
    a.org_id,
    true
  );

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================
-- Row Level Security
-- ============================================================
alter table organizations enable row level security;
alter table profiles enable row level security;
alter table courses enable row level security;
alter table lessons enable row level security;
alter table lesson_progress enable row level security;
alter table allowed_emails enable row level security;
alter table course_deadlines enable row level security;
alter table organization_courses enable row level security;
alter table audit_logs enable row level security;

create or replace function public.is_active_user()
returns boolean
language sql
security definer set search_path = public
stable
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid() and active = true
  );
$$;

-- 自分が admin かどうかを返すヘルパー（RLS の再帰を避けるため security definer）
create or replace function public.is_admin()
returns boolean
language sql
security definer set search_path = public
stable
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid() and role = 'admin' and active = true
  );
$$;

create or replace function public.current_org_id()
returns uuid
language sql
security definer set search_path = public
stable
as $$
  select p.org_id from public.profiles p where p.id = auth.uid();
$$;

create or replace function public.can_access_course(target_course_id uuid)
returns boolean
language sql
security definer set search_path = public
stable
as $$
  select public.is_active_user()
    and (
      public.is_admin()
      or exists (
        select 1
        from public.organization_courses oc
        join public.organizations o on o.id = oc.org_id
        join public.courses c on c.id = oc.course_id
        where oc.org_id = public.current_org_id()
          and oc.course_id = target_course_id
          and o.access_enabled = true
          and c.published = true
      )
    );
$$;

-- 自社メンバーの受講状況を管理できるか
create or replace function public.can_manage_org()
returns boolean
language sql
security definer set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid()
      and role in ('admin', 'manager')
      and active = true
  );
$$;

-- 同じ組織の user_id 一覧（admin ダッシュボード用）
create or replace function public.same_org_user_ids()
returns setof uuid
language sql
security definer set search_path = public
stable
as $$
  select p.id from public.profiles p
  where p.org_id = (select org_id from public.profiles where id = auth.uid());
$$;

create or replace function public.user_belongs_to_org(
  target_user_id uuid,
  target_org_id uuid
)
returns boolean
language sql
security definer set search_path = public
stable
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = target_user_id
      and p.org_id = target_org_id
  );
$$;

-- profiles: 本人と管理者のみ。一般メンバーは匿名化された集計RPCを使う
create policy "profiles_select_own" on profiles
  for select using (id = auth.uid());
create policy "profiles_select_org_manager" on profiles
  for select using (
    public.is_admin()
    or (
      public.can_manage_org()
      and id in (select public.same_org_user_ids())
    )
  );

-- allowed_emails: 運営adminは全組織、managerは自組織を閲覧可。変更はRPC経由
create policy "allowed_admin_all" on allowed_emails
  for all using (public.is_admin()) with check (public.is_admin());
create policy "allowed_manager_select" on allowed_emails
  for select using (
    public.can_manage_org()
    and org_id = public.current_org_id()
  );

-- organizations: 自分の所属組織を読める
create policy "orgs_select_own" on organizations
  for select using (
    id = (select org_id from public.profiles where id = auth.uid())
  );
create policy "orgs_admin_all" on organizations
  for all using (public.is_admin()) with check (public.is_admin());

-- organization_courses: 自組織分は閲覧可。運営 admin は割り当てを管理可
create policy "organization_courses_select_own" on organization_courses
  for select using (
    public.is_admin() or org_id = public.current_org_id()
  );
create policy "organization_courses_admin_all" on organization_courses
  for all using (public.is_admin()) with check (public.is_admin());

-- courses / lessons: 自組織に割り当てられた公開講座のみ閲覧可
create policy "courses_select_assigned" on courses
  for select using (published = true and public.can_access_course(id));
create policy "lessons_select_assigned" on lessons
  for select using (public.can_access_course(course_id));

-- courses / lessons: admin は全件の作成・編集・削除・閲覧（未公開含む）が可能
create policy "courses_admin_all" on courses
  for all using (public.is_admin()) with check (public.is_admin());
create policy "lessons_admin_all" on lessons
  for all using (public.is_admin()) with check (public.is_admin());

-- lesson_progress: 自分は読み書き可。詳細閲覧は運営adminとmanagerのみ
create policy "progress_rw_own" on lesson_progress
  for all using (
    public.is_active_user() and user_id = auth.uid()
  ) with check (
    public.is_active_user() and user_id = auth.uid()
  );
create policy "progress_select_org_manager" on lesson_progress
  for select using (
    public.is_admin()
    or (
      public.can_manage_org()
      and user_id in (select public.same_org_user_ids())
    )
  );

-- course_deadlines: 本人と管理者のみ閲覧可
create policy "deadlines_select_own_org" on course_deadlines
  for select using (
    public.is_admin()
    or user_id = auth.uid()
    or (
      public.can_manage_org()
      and org_id = public.current_org_id()
    )
  );
create policy "deadlines_manage_own_org" on course_deadlines
  for all using (
    public.is_admin()
    or (
      public.can_manage_org()
      and org_id = public.current_org_id()
      and public.user_belongs_to_org(user_id, org_id)
    )
  ) with check (
    public.is_admin()
    or (
      public.can_manage_org()
      and org_id = public.current_org_id()
      and public.user_belongs_to_org(user_id, org_id)
    )
  );

create policy "audit_logs_select_org_manager" on audit_logs
  for select using (
    public.is_admin()
    or (
      public.can_manage_org()
      and org_id = public.current_org_id()
    )
  );

alter table course_deadlines
  add constraint course_deadlines_assignment_fkey
  foreign key (org_id, course_id)
  references organization_courses (org_id, course_id)
  on delete cascade;

create or replace function public.set_organization_courses(
  target_org_id uuid,
  target_course_ids uuid[]
)
returns void
language plpgsql
security definer set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'forbidden';
  end if;

  delete from public.organization_courses
  where org_id = target_org_id
    and not (course_id = any(coalesce(target_course_ids, array[]::uuid[])));

  insert into public.organization_courses (org_id, course_id, assigned_by)
  select target_org_id, c.id, auth.uid()
  from public.courses c
  where c.id = any(coalesce(target_course_ids, array[]::uuid[]))
    and c.published = true
  on conflict (org_id, course_id) do nothing;
end;
$$;

create or replace function public.get_team_progress()
returns table (
  user_id uuid,
  full_name text,
  completed_count bigint,
  total_count bigint,
  percentage integer
)
language sql
security definer set search_path = public
stable
as $$
  with team as (
    select
      p.id as user_id,
      coalesce(nullif(p.full_name, ''), '名前未設定') as full_name,
      count(distinct lp.lesson_id) filter (
        where lp.completed = true
      ) as completed_count,
      count(distinct l.id) as total_count,
      case
        when count(distinct l.id) = 0 then 0
        else round(
          count(distinct lp.lesson_id) filter (where lp.completed = true)
          * 100.0 / count(distinct l.id)
        )::integer
      end as percentage
    from public.profiles p
    left join public.organization_courses oc on oc.org_id = p.org_id
    left join public.courses c
      on c.id = oc.course_id
     and c.published = true
    left join public.lessons l on l.course_id = c.id
    left join public.lesson_progress lp
      on lp.user_id = p.id
     and lp.lesson_id = l.id
    where public.is_active_user()
      and p.active = true
      and p.org_id = public.current_org_id()
    group by p.id, p.full_name
  )
  select *
  from team
  order by percentage desc, full_name;
$$;

create or replace function public.manage_organization_invite(
  target_org_id uuid,
  target_email text,
  target_role text,
  target_active boolean
)
returns void
language plpgsql
security definer set search_path = public
as $$
declare
  actor public.profiles%rowtype;
  existing public.allowed_emails%rowtype;
  target_profile_id uuid;
  normalized_email text := lower(trim(target_email));
begin
  select * into actor
  from public.profiles
  where id = auth.uid();

  if not found or not actor.active or actor.role not in ('admin', 'manager') then
    raise exception 'forbidden';
  end if;
  if actor.role = 'manager' and actor.org_id <> target_org_id then
    raise exception 'forbidden';
  end if;
  if target_role not in ('manager', 'member') then
    raise exception 'invalid_role';
  end if;
  if normalized_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
    raise exception 'invalid_email';
  end if;

  select * into existing
  from public.allowed_emails
  where lower(email) = normalized_email;

  if found and existing.role = 'admin' then
    raise exception 'platform_admin_locked';
  end if;
  if found and existing.org_id <> target_org_id then
    raise exception 'email_belongs_to_other_org';
  end if;

  select id into target_profile_id
  from public.profiles
  where lower(email) = normalized_email;

  if target_profile_id = auth.uid()
     and (target_role <> actor.role or not target_active) then
    raise exception 'cannot_change_self';
  end if;

  if found then
    update public.allowed_emails
    set role = target_role,
        active = target_active,
        updated_at = now()
    where email = existing.email;
  else
    insert into public.allowed_emails (
      email,
      role,
      org_id,
      active,
      invited_by,
      updated_at
    )
    values (
      normalized_email,
      target_role,
      target_org_id,
      target_active,
      auth.uid(),
      now()
    );
  end if;

  update public.profiles
  set role = target_role,
      org_id = target_org_id,
      active = target_active
  where lower(email) = normalized_email
    and role <> 'admin';
end;
$$;

create or replace function public.delete_organization_member(
  target_org_id uuid,
  target_email text
)
returns void
language plpgsql
security definer set search_path = public
as $$
declare
  actor public.profiles%rowtype;
  target_invite public.allowed_emails%rowtype;
  target_user_id uuid;
  normalized_email text := lower(trim(target_email));
begin
  select * into actor
  from public.profiles
  where id = auth.uid();

  if not found or not actor.active or actor.role not in ('admin', 'manager') then
    raise exception 'forbidden';
  end if;
  if actor.role = 'manager' and actor.org_id <> target_org_id then
    raise exception 'forbidden';
  end if;

  select * into target_invite
  from public.allowed_emails
  where lower(email) = normalized_email
    and org_id = target_org_id;

  if not found then
    raise exception 'member_not_found';
  end if;
  if target_invite.role = 'admin' then
    raise exception 'platform_admin_locked';
  end if;

  select id into target_user_id
  from public.profiles
  where lower(email) = normalized_email
    and org_id = target_org_id;

  if target_user_id = auth.uid() then
    raise exception 'cannot_delete_self';
  end if;

  delete from auth.users where id = target_user_id;
  delete from public.allowed_emails
  where lower(email) = normalized_email
    and org_id = target_org_id;
end;
$$;

create or replace function public.audit_management_change()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  target_org uuid;
  event_action text;
  event_target_id text;
  event_metadata jsonb;
begin
  if auth.uid() is null then
    if tg_op = 'DELETE' then return old; else return new; end if;
  end if;

  if tg_table_name = 'allowed_emails' then
    target_org := coalesce(new.org_id, old.org_id);
    event_action := case tg_op
      when 'INSERT' then 'invite.created'
      when 'UPDATE' then 'invite.updated'
      else 'invite.deleted'
    end;
    event_target_id := coalesce(new.email, old.email);
    event_metadata := jsonb_build_object(
      'email', coalesce(new.email, old.email),
      'role_before', old.role,
      'role_after', new.role,
      'active_before', old.active,
      'active_after', new.active
    );
  elsif tg_table_name = 'course_deadlines' then
    target_org := coalesce(new.org_id, old.org_id);
    event_action := case tg_op
      when 'INSERT' then 'deadline.created'
      when 'UPDATE' then 'deadline.updated'
      else 'deadline.deleted'
    end;
    event_target_id := coalesce(new.id, old.id)::text;
    event_metadata := jsonb_build_object(
      'user_id', coalesce(new.user_id, old.user_id),
      'course_id', coalesce(new.course_id, old.course_id),
      'due_date_before', old.due_date,
      'due_date_after', new.due_date
    );
  elsif tg_table_name = 'organization_courses' then
    target_org := coalesce(new.org_id, old.org_id);
    event_action := case tg_op
      when 'INSERT' then 'course.assigned'
      else 'course.unassigned'
    end;
    event_target_id := coalesce(new.course_id, old.course_id)::text;
    event_metadata := jsonb_build_object(
      'course_id', coalesce(new.course_id, old.course_id)
    );
  else
    target_org := coalesce(new.id, old.id);
    event_action := 'organization.access_updated';
    event_target_id := target_org::text;
    event_metadata := jsonb_build_object(
      'access_before', old.access_enabled,
      'access_after', new.access_enabled
    );
  end if;

  insert into public.audit_logs (
    org_id,
    actor_id,
    action,
    target_type,
    target_id,
    metadata
  )
  values (
    target_org,
    auth.uid(),
    event_action,
    tg_table_name,
    event_target_id,
    event_metadata
  );

  if tg_op = 'DELETE' then return old; else return new; end if;
end;
$$;

drop trigger if exists audit_allowed_emails on allowed_emails;
create trigger audit_allowed_emails
after insert or update or delete on allowed_emails
for each row execute function public.audit_management_change();

drop trigger if exists audit_course_deadlines on course_deadlines;
create trigger audit_course_deadlines
after insert or update or delete on course_deadlines
for each row execute function public.audit_management_change();

drop trigger if exists audit_organization_courses on organization_courses;
create trigger audit_organization_courses
after insert or delete on organization_courses
for each row execute function public.audit_management_change();

drop trigger if exists audit_organization_access on organizations;
create trigger audit_organization_access
after update of access_enabled on organizations
for each row
when (old.access_enabled is distinct from new.access_enabled)
execute function public.audit_management_change();

revoke all on function public.get_team_progress() from public;
grant execute on function public.get_team_progress() to authenticated;
revoke all on function public.manage_organization_invite(uuid, text, text, boolean) from public;
grant execute on function public.manage_organization_invite(uuid, text, text, boolean)
  to authenticated;
revoke all on function public.delete_organization_member(uuid, text) from public;
grant execute on function public.delete_organization_member(uuid, text)
  to authenticated;
grant select on table public.audit_logs to authenticated;
