-- Member privacy, organization invite management, suspension, and audit logs.

alter table public.profiles
  add column if not exists active boolean not null default true;

alter table public.allowed_emails
  add column if not exists active boolean not null default true,
  add column if not exists invited_by uuid references auth.users on delete set null,
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists allowed_emails_lower_email_key
  on public.allowed_emails (lower(email));

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  org_id uuid references public.organizations on delete set null,
  actor_id uuid references auth.users on delete set null,
  action text not null,
  target_type text not null,
  target_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_logs_org_created
  on public.audit_logs (org_id, created_at desc);

alter table public.audit_logs enable row level security;

create or replace function public.is_active_user()
returns boolean
language sql
security definer set search_path = public
stable
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid() and active = true
  );
$$;

create or replace function public.is_admin()
returns boolean
language sql
security definer set search_path = public
stable
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid() and role = 'admin' and active = true
  );
$$;

create or replace function public.can_manage_org()
returns boolean
language sql
security definer set search_path = public
stable
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role in ('admin', 'manager')
      and active = true
  );
$$;

create or replace function public.can_access_course(target_course_id uuid)
returns boolean
language sql
security definer set search_path = public
stable
as $$
  select public.is_active_user()
    and (
      public.is_admin()
      or exists (
        select 1
        from public.organization_courses oc
        join public.organizations o on o.id = oc.org_id
        join public.courses c on c.id = oc.course_id
        where oc.org_id = public.current_org_id()
          and oc.course_id = target_course_id
          and o.access_enabled = true
          and c.published = true
      )
    );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  a public.allowed_emails%rowtype;
begin
  select * into a
  from public.allowed_emails
  where lower(email) = lower(new.email);

  if not found or not a.active then
    raise exception 'not_allowed: % は招待されていません', new.email;
  end if;

  insert into public.profiles (
    id,
    email,
    full_name,
    role,
    org_id,
    active
  )
  values (
    new.id,
    new.email,
    new.raw_user_meta_data ->> 'full_name',
    a.role,
    a.org_id,
    true
  );

  return new;
end;
$$;

drop policy if exists "profiles_select_same_org" on public.profiles;
drop policy if exists "profiles_select_org_manager" on public.profiles;
create policy "profiles_select_org_manager" on public.profiles
  for select using (
    public.is_admin()
    or (
      public.can_manage_org()
      and id in (select public.same_org_user_ids())
    )
  );

drop policy if exists "progress_rw_own" on public.lesson_progress;
create policy "progress_rw_own" on public.lesson_progress
  for all using (
    public.is_active_user() and user_id = auth.uid()
  ) with check (
    public.is_active_user() and user_id = auth.uid()
  );

drop policy if exists "progress_select_same_org" on public.lesson_progress;
drop policy if exists "progress_select_org_manager" on public.lesson_progress;
create policy "progress_select_org_manager" on public.lesson_progress
  for select using (
    public.is_admin()
    or (
      public.can_manage_org()
      and user_id in (select public.same_org_user_ids())
    )
  );

drop policy if exists "deadlines_select_own_org" on public.course_deadlines;
create policy "deadlines_select_own_org" on public.course_deadlines
  for select using (
    public.is_admin()
    or user_id = auth.uid()
    or (
      public.can_manage_org()
      and org_id = public.current_org_id()
    )
  );

drop policy if exists "allowed_manager_select" on public.allowed_emails;
create policy "allowed_manager_select" on public.allowed_emails
  for select using (
    public.can_manage_org()
    and org_id = public.current_org_id()
  );

drop policy if exists "audit_logs_select_org_manager" on public.audit_logs;
create policy "audit_logs_select_org_manager" on public.audit_logs
  for select using (
    public.is_admin()
    or (
      public.can_manage_org()
      and org_id = public.current_org_id()
    )
  );

create or replace function public.get_team_progress()
returns table (
  user_id uuid,
  full_name text,
  completed_count bigint,
  total_count bigint,
  percentage integer
)
language sql
security definer set search_path = public
stable
as $$
  with team as (
    select
      p.id as user_id,
      coalesce(nullif(p.full_name, ''), '名前未設定') as full_name,
      count(distinct lp.lesson_id) filter (
        where lp.completed = true
      ) as completed_count,
      count(distinct l.id) as total_count,
      case
        when count(distinct l.id) = 0 then 0
        else round(
          count(distinct lp.lesson_id) filter (where lp.completed = true)
          * 100.0 / count(distinct l.id)
        )::integer
      end as percentage
    from public.profiles p
    left join public.organization_courses oc on oc.org_id = p.org_id
    left join public.courses c
      on c.id = oc.course_id
     and c.published = true
    left join public.lessons l on l.course_id = c.id
    left join public.lesson_progress lp
      on lp.user_id = p.id
     and lp.lesson_id = l.id
    where public.is_active_user()
      and p.active = true
      and p.org_id = public.current_org_id()
    group by p.id, p.full_name
  )
  select *
  from team
  order by percentage desc, full_name;
$$;

create or replace function public.manage_organization_invite(
  target_org_id uuid,
  target_email text,
  target_role text,
  target_active boolean
)
returns void
language plpgsql
security definer set search_path = public
as $$
declare
  actor public.profiles%rowtype;
  existing public.allowed_emails%rowtype;
  target_profile_id uuid;
  normalized_email text := lower(trim(target_email));
begin
  select * into actor from public.profiles where id = auth.uid();

  if not found or not actor.active or actor.role not in ('admin', 'manager') then
    raise exception 'forbidden';
  end if;
  if actor.role = 'manager' and actor.org_id <> target_org_id then
    raise exception 'forbidden';
  end if;
  if target_role not in ('manager', 'member') then
    raise exception 'invalid_role';
  end if;
  if normalized_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
    raise exception 'invalid_email';
  end if;

  select * into existing
  from public.allowed_emails
  where lower(email) = normalized_email;

  if found and existing.role = 'admin' then
    raise exception 'platform_admin_locked';
  end if;
  if found and existing.org_id <> target_org_id then
    raise exception 'email_belongs_to_other_org';
  end if;

  select id into target_profile_id
  from public.profiles
  where lower(email) = normalized_email;

  if target_profile_id = auth.uid()
     and (target_role <> actor.role or not target_active) then
    raise exception 'cannot_change_self';
  end if;

  if found then
    update public.allowed_emails
    set role = target_role,
        active = target_active,
        updated_at = now()
    where email = existing.email;
  else
    insert into public.allowed_emails (
      email,
      role,
      org_id,
      active,
      invited_by,
      updated_at
    )
    values (
      normalized_email,
      target_role,
      target_org_id,
      target_active,
      auth.uid(),
      now()
    );
  end if;

  update public.profiles
  set role = target_role,
      org_id = target_org_id,
      active = target_active
  where lower(email) = normalized_email
    and role <> 'admin';
end;
$$;

create or replace function public.delete_organization_member(
  target_org_id uuid,
  target_email text
)
returns void
language plpgsql
security definer set search_path = public
as $$
declare
  actor public.profiles%rowtype;
  target_invite public.allowed_emails%rowtype;
  target_user_id uuid;
  normalized_email text := lower(trim(target_email));
begin
  select * into actor from public.profiles where id = auth.uid();

  if not found or not actor.active or actor.role not in ('admin', 'manager') then
    raise exception 'forbidden';
  end if;
  if actor.role = 'manager' and actor.org_id <> target_org_id then
    raise exception 'forbidden';
  end if;

  select * into target_invite
  from public.allowed_emails
  where lower(email) = normalized_email
    and org_id = target_org_id;

  if not found then
    raise exception 'member_not_found';
  end if;
  if target_invite.role = 'admin' then
    raise exception 'platform_admin_locked';
  end if;

  select id into target_user_id
  from public.profiles
  where lower(email) = normalized_email
    and org_id = target_org_id;

  if target_user_id = auth.uid() then
    raise exception 'cannot_delete_self';
  end if;

  delete from auth.users where id = target_user_id;
  delete from public.allowed_emails
  where lower(email) = normalized_email
    and org_id = target_org_id;
end;
$$;

create or replace function public.audit_management_change()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  target_org uuid;
  event_action text;
  event_target_id text;
  event_metadata jsonb;
begin
  if auth.uid() is null then
    if tg_op = 'DELETE' then return old; else return new; end if;
  end if;

  if tg_table_name = 'allowed_emails' then
    target_org := coalesce(new.org_id, old.org_id);
    event_action := case tg_op
      when 'INSERT' then 'invite.created'
      when 'UPDATE' then 'invite.updated'
      else 'invite.deleted'
    end;
    event_target_id := coalesce(new.email, old.email);
    event_metadata := jsonb_build_object(
      'email', coalesce(new.email, old.email),
      'role_before', old.role,
      'role_after', new.role,
      'active_before', old.active,
      'active_after', new.active
    );
  elsif tg_table_name = 'course_deadlines' then
    target_org := coalesce(new.org_id, old.org_id);
    event_action := case tg_op
      when 'INSERT' then 'deadline.created'
      when 'UPDATE' then 'deadline.updated'
      else 'deadline.deleted'
    end;
    event_target_id := coalesce(new.id, old.id)::text;
    event_metadata := jsonb_build_object(
      'user_id', coalesce(new.user_id, old.user_id),
      'course_id', coalesce(new.course_id, old.course_id),
      'due_date_before', old.due_date,
      'due_date_after', new.due_date
    );
  elsif tg_table_name = 'organization_courses' then
    target_org := coalesce(new.org_id, old.org_id);
    event_action := case tg_op
      when 'INSERT' then 'course.assigned'
      else 'course.unassigned'
    end;
    event_target_id := coalesce(new.course_id, old.course_id)::text;
    event_metadata := jsonb_build_object(
      'course_id', coalesce(new.course_id, old.course_id)
    );
  else
    target_org := coalesce(new.id, old.id);
    event_action := 'organization.access_updated';
    event_target_id := target_org::text;
    event_metadata := jsonb_build_object(
      'access_before', old.access_enabled,
      'access_after', new.access_enabled
    );
  end if;

  insert into public.audit_logs (
    org_id,
    actor_id,
    action,
    target_type,
    target_id,
    metadata
  )
  values (
    target_org,
    auth.uid(),
    event_action,
    tg_table_name,
    event_target_id,
    event_metadata
  );

  if tg_op = 'DELETE' then return old; else return new; end if;
end;
$$;

drop trigger if exists audit_allowed_emails on public.allowed_emails;
create trigger audit_allowed_emails
after insert or update or delete on public.allowed_emails
for each row execute function public.audit_management_change();

drop trigger if exists audit_course_deadlines on public.course_deadlines;
create trigger audit_course_deadlines
after insert or update or delete on public.course_deadlines
for each row execute function public.audit_management_change();

drop trigger if exists audit_organization_courses on public.organization_courses;
create trigger audit_organization_courses
after insert or delete on public.organization_courses
for each row execute function public.audit_management_change();

drop trigger if exists audit_organization_access on public.organizations;
create trigger audit_organization_access
after update of access_enabled on public.organizations
for each row
when (old.access_enabled is distinct from new.access_enabled)
execute function public.audit_management_change();

revoke all on function public.get_team_progress() from public;
grant execute on function public.get_team_progress() to authenticated;
revoke all on function public.manage_organization_invite(uuid, text, text, boolean) from public;
grant execute on function public.manage_organization_invite(uuid, text, text, boolean)
  to authenticated;
revoke all on function public.delete_organization_member(uuid, text) from public;
grant execute on function public.delete_organization_member(uuid, text)
  to authenticated;
grant select on table public.audit_logs to authenticated;
